// GENERATED BY `kb guards` — DO NOT EDIT.
// Source of truth: anchoring.config.json → architecture
// kb-guards-hash: bfccd839be2f69e4
// Regenerate with: npx kb guards
export default [
  {
    files: [
      'src/cli.ts/**/*',
      'src/cli-upstream.ts/**/*',
      'src/cli-pack.ts/**/*',
      'src/cli-promote.ts/**/*',
      'src/cli-brief.ts/**/*',
      'src/cli-verify.ts/**/*',
      'src/render.ts/**/*',
      'src/render-brief.ts/**/*',
      'src/init.ts/**/*',
      'src/agents.ts/**/*',
      'src/config.ts/**/*',
      'src/config-architecture.ts/**/*',
      'src/store.ts/**/*',
      'src/verify.ts/**/*',
      'src/verify-upstream.ts/**/*',
      'src/verify-hazard.ts/**/*',
      'src/finding.ts/**/*',
      'src/why.ts/**/*',
      'src/ctx.ts/**/*',
      'src/done.ts/**/*',
      'src/guards.ts/**/*',
      'src/owners.ts/**/*',
      'src/model.ts/**/*',
      'src/frontmatter.ts/**/*',
      'src/anchors.ts/**/*',
      'src/upstream.ts/**/*',
      'src/ask.ts/**/*',
      'src/pack.ts/**/*',
      'src/promote.ts/**/*',
      'src/brief.ts/**/*',
      'src/since.ts/**/*',
      'src/fingerprint.ts/**/*',
      'src/fnv.ts/**/*',
      'src/root.ts/**/*',
      'src/git.ts/**/*',
      'src/loader.ts/**/*',
      'src/resolver.ts/**/*',
      'src/session.ts/**/*',
      'src/pack-source.ts/**/*',
      'src/brief-source.ts/**/*',
    ],
    rules: {
      'max-lines': [
        'error',
        {
          max: 400,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
      'max-lines-per-function': [
        'error',
        {
          max: 50,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['**/*.test.*', '**/*.spec.*'],
    rules: {
      'max-lines': [
        'error',
        {
          max: 400,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
      'max-lines-per-function': 'off',
    },
  },
  {
    files: [
      'src/config.ts/**/*',
      'src/config-architecture.ts/**/*',
      'src/store.ts/**/*',
      'src/verify.ts/**/*',
      'src/verify-upstream.ts/**/*',
      'src/verify-hazard.ts/**/*',
      'src/finding.ts/**/*',
      'src/why.ts/**/*',
      'src/ctx.ts/**/*',
      'src/done.ts/**/*',
      'src/guards.ts/**/*',
      'src/owners.ts/**/*',
      'src/model.ts/**/*',
      'src/frontmatter.ts/**/*',
      'src/anchors.ts/**/*',
      'src/upstream.ts/**/*',
      'src/ask.ts/**/*',
      'src/pack.ts/**/*',
      'src/promote.ts/**/*',
      'src/brief.ts/**/*',
      'src/since.ts/**/*',
      'src/fingerprint.ts/**/*',
      'src/fnv.ts/**/*',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
          {
            group: ['node:fs', 'node:fs/*'],
            message: 'domain is the pure layer: pass the value in as an argument instead of importing node:fs.',
          },
          {
            group: ['node:child_process', 'node:child_process/*'],
            message: 'domain is the pure layer: pass the value in as an argument instead of importing node:child_process.',
          },
          {
            group: ['node:http', 'node:http/*'],
            message: 'domain is the pure layer: pass the value in as an argument instead of importing node:http.',
          },
          {
            group: ['node:https', 'node:https/*'],
            message: 'domain is the pure layer: pass the value in as an argument instead of importing node:https.',
          },
          {
            group: ['node:crypto', 'node:crypto/*'],
            message: 'domain is the pure layer: pass the value in as an argument instead of importing node:crypto.',
          },
          ],
        },
      ],
      'no-restricted-globals': [
        'error',
        {
          name: 'Date',
          message: 'domain is the pure layer: pass the value in as an argument instead of using global Date.',
        },
        {
          name: 'fetch',
          message: 'domain is the pure layer: pass the value in as an argument instead of using global fetch.',
        },
        {
          name: 'crypto',
          message: 'domain is the pure layer: pass the value in as an argument instead of using global crypto.',
        },
      ],
      'no-restricted-properties': [
        'error',
        {
          object: 'Math',
          property: 'random',
          message: 'domain is the pure layer: pass the value in as an argument instead of calling Math.random.',
        },
        {
          object: 'Date',
          property: 'now',
          message: 'domain is the pure layer: pass the value in as an argument instead of calling Date.now.',
        },
      ],
    },
  }
]
