// GENERATED BY `kb guards` — DO NOT EDIT.
// Source of truth: anchoring.config.json → architecture
// kb-guards-hash: e805a788ea98bd18
// Regenerate with: npx kb guards
export default [
  {
    files: [
      'src/**/*',
    ],
    rules: {
      'max-lines': [
        'error',
        {
          max: 400,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
      'max-lines-per-function': [
        'error',
        {
          max: 50,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['**/*.test.*', '**/*.spec.*'],
    rules: {
      'max-lines': [
        'error',
        {
          max: 400,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
      'max-lines-per-function': 'off',
    },
  },
  {
    files: ['src/ask.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 57,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/cli-promote.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 64,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/cli-upstream.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 70,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/cli.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 174,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/config-architecture.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 181,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/config.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 231,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/ctx.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 61,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/guards.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 71,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/init.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 214,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/owners.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 55,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/pack.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 62,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/promote.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 66,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/render.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 52,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/upstream.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 67,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/verify-hazard.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 99,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: ['src/verify-upstream.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: 100,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  },
  {
    files: [
      'src/**/*',
    ],
    ignores: [
      'src/root.ts',
      'src/git.ts',
      'src/loader.ts',
      'src/resolver.ts',
      'src/session.ts',
      'src/pack-source.ts',
      'src/brief-source.ts',
      'src/init.ts',
      'src/cli-upstream.ts',
      'src/cli-pack.ts',
      'src/cli-promote.ts',
      'src/eslint-probe.ts',
      'src/skills-source.ts',
      '**/*.test.*',
      '**/*.spec.*',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
          {
            group: ['node:fs', 'node:fs/*'],
            message: 'Core modules must not import node:fs directly; pass I/O dependencies (INV-INJECTED-IO).',
          },
          {
            group: ['node:child_process', 'node:child_process/*'],
            message: 'Core modules must not import node:child_process directly; pass I/O dependencies (INV-INJECTED-IO).',
          },
          {
            group: ['node:http', 'node:http/*'],
            message: 'Core modules must not import node:http directly; pass I/O dependencies (INV-INJECTED-IO).',
          },
          {
            group: ['node:https', 'node:https/*'],
            message: 'Core modules must not import node:https directly; pass I/O dependencies (INV-INJECTED-IO).',
          },
          {
            group: ['node:crypto', 'node:crypto/*'],
            message: 'Core modules must not import node:crypto directly; pass I/O dependencies (INV-INJECTED-IO).',
          },
          ],
        },
      ],
    },
  },
  {
    files: [
      'src/**/*',
    ],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: ':matches(Program, Program > ExportNamedDeclaration) > VariableDeclaration[kind!="const"] > VariableDeclarator[id.name="config"]',
          message: 'Module-scope mutable `config` is forbidden (INV-CONFIG-THREADED). Pass config as a parameter.',
        },
      ],
    },
  },
  {
    files: [
      'src/config.ts',
      'src/config-architecture.ts',
      'src/store.ts',
      'src/verify-upstream.ts',
      'src/verify-hazard.ts',
      'src/finding.ts',
      'src/guards.ts',
      'src/model.ts',
      'src/frontmatter.ts',
      'src/anchors.ts',
      'src/upstream.ts',
      'src/pack.ts',
      'src/promote.ts',
      'src/verify-tags.ts',
      'src/brief.ts',
      'src/since.ts',
      'src/fingerprint.ts',
      'src/fnv.ts',
      'src/guards-live.ts',
      'src/skills.ts',
    ],
    ignores: ['**/*.test.*', '**/*.spec.*'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: ':matches(Program, Program > ExportNamedDeclaration) > VariableDeclaration[kind!="const"] > VariableDeclarator[id.name="config"]',
          message: 'Module-scope mutable `config` is forbidden (INV-CONFIG-THREADED). Pass config as a parameter.',
        },
        {
          selector: 'NewExpression[callee.name="Date"]',
          message: 'domain is the pure layer: pass the value in as an argument instead of constructing a Date.',
        },
      ],
      'no-restricted-globals': [
        'error',
        {
          name: 'fetch',
          message: 'domain is the pure layer: pass the value in as an argument instead of using global fetch.',
        },
        {
          name: 'crypto',
          message: 'domain is the pure layer: pass the value in as an argument instead of using global crypto.',
        },
      ],
      'no-restricted-properties': [
        'error',
        {
          object: 'Math',
          property: 'random',
          message: 'domain is the pure layer: pass the value in as an argument instead of calling Math.random.',
        },
        {
          object: 'Date',
          property: 'now',
          message: 'domain is the pure layer: pass the value in as an argument instead of calling Date.now.',
        },
      ],
    },
  }
]
