import { describe, expect, test } from 'vitest'
import { mkdtempSync, writeFileSync, rmSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { planGuards, guardsHash, checkGuards } from './guards.js'
import { defaultConfig, type Architecture } from './config.js'
import { run } from './cli.js'

function makeTemp(prefix: string): string {
  return mkdtempSync(join(tmpdir(), prefix))
}

const SAMPLE_ARCH: Architecture = {
  layers: [
    { name: 'ui', paths: ['src/ui/', 'apps/'], pure: false },
    { name: 'app', paths: ['src/app/'], pure: false },
    { name: 'domain', paths: ['src/domain/'], pure: true },
    { name: 'infra', paths: ['src/infra/'], pure: false },
  ],
  moduleRoots: ['src/modules/', 'packages/'],
  entryPoints: ['index.ts', 'index.tsx', 'index.js'],
  maxFileLines: 400,
  maxFunctionLines: 50,
  maxFunctionLinesBaseline: {},
  ioExemptions: [],
  restrictedSyntax: [],
  ioMessage: 'Import {module} only from a declared I/O adapter; elsewhere, pass the value in as an argument.',
  impureImports: ['node:fs', 'node:child_process', 'node:http', 'node:https', 'node:crypto'],
}

describe('guardsHash', () => {
  test('header appears verbatim in both files with a 16-hex-character hash', () => {
    const config = {
      ...defaultConfig('/root'),
      architecture: SAMPLE_ARCH,
    }
    const plan = planGuards(config)
    expect(plan.files.length).toBe(2)

    for (const file of plan.files) {
      expect(file.body).toContain('// GENERATED BY `kb guards` — DO NOT EDIT.')
      expect(file.body).toContain('// Source of truth: anchoring.config.json → architecture')
      expect(file.body).toContain('// Regenerate with: npx kb guards')
      const hashMatch = file.body.match(/\/\/ kb-guards-hash: ([0-9a-f]{16})/)
      expect(hashMatch).not.toBeNull()
    }
  })

  test('guardsHash is stable across key order in source object', () => {
    const archA: Architecture = {
      layers: [{ name: 'a', paths: ['src/a/'], pure: false }],
      moduleRoots: ['src/m/'],
      entryPoints: ['index.ts'],
      maxFileLines: 300,
      maxFunctionLines: 40,
      maxFunctionLinesBaseline: {},
      ioExemptions: [],
      restrictedSyntax: [],
      ioMessage: 'Import {module} only from a declared I/O adapter; elsewhere, pass the value in as an argument.',
      impureImports: ['node:fs'],
    }

    const archB: Architecture = {
      maxFunctionLines: 40,
      maxFunctionLinesBaseline: {},
      ioExemptions: [],
      restrictedSyntax: [],
      ioMessage: 'Import {module} only from a declared I/O adapter; elsewhere, pass the value in as an argument.',
      entryPoints: ['index.ts'],
      layers: [{ pure: false, paths: ['src/a/'], name: 'a' }],
      impureImports: ['node:fs'],
      maxFileLines: 300,
      moduleRoots: ['src/m/'],
    }

    expect(guardsHash(archA)).toBe(guardsHash(archB))
  })

  test('guardsHash changes when any architecture value changes', () => {
    const base = SAMPLE_ARCH
    const baseHash = guardsHash(base)

    const diffLayers = guardsHash({ ...base, layers: [] })
    expect(diffLayers).not.toBe(baseHash)

    const diffRoots = guardsHash({ ...base, moduleRoots: [] })
    expect(diffRoots).not.toBe(baseHash)

    const diffEntries = guardsHash({ ...base, entryPoints: ['main.ts'] })
    expect(diffEntries).not.toBe(baseHash)

    const diffMaxFiles = guardsHash({ ...base, maxFileLines: 500 })
    expect(diffMaxFiles).not.toBe(baseHash)

    const diffMaxFuncs = guardsHash({ ...base, maxFunctionLines: 60 })
    expect(diffMaxFuncs).not.toBe(baseHash)

    const diffImpure = guardsHash({ ...base, impureImports: ['node:fs'] })
    expect(diffImpure).not.toBe(baseHash)
  })
})

describe('planGuards generation rules', () => {
  test('empty architecture produces both files, forbidden with no-circular, and nothing configured comment', () => {
    const config = {
      ...defaultConfig('/root'),
      architecture: {
        layers: [],
        moduleRoots: [],
        entryPoints: ['index.ts'],
        maxFileLines: 400,
        maxFunctionLines: 50,
        maxFunctionLinesBaseline: {},
        ioExemptions: [],
        restrictedSyntax: [],
        ioMessage: 'Import {module} only from a declared I/O adapter; elsewhere, pass the value in as an argument.',
        impureImports: [],
      },
    }
    const plan = planGuards(config)
    expect(plan.files.length).toBe(2)
    const depcruise = plan.files.find((f) => f.path === 'anchoring.depcruise.cjs')
    expect(depcruise).toBeDefined()
    expect(depcruise?.body).toContain('// No layers or moduleRoots configured yet in anchoring.config.json.')
    expect(depcruise?.body).toContain("name: 'no-circular'")
  })

  test('four ordered layers produce exactly six ordered-pair rules, named for direction crossed', () => {
    const config = {
      ...defaultConfig('/root'),
      architecture: SAMPLE_ARCH,
    }
    const plan = planGuards(config)
    const depcruise = plan.files.find((f) => f.path === 'anchoring.depcruise.cjs')?.body ?? ''

    const expectedPairs = [
      'layer-app-must-not-import-ui',
      'layer-domain-must-not-import-ui',
      'layer-infra-must-not-import-ui',
      'layer-domain-must-not-import-app',
      'layer-infra-must-not-import-app',
      'layer-infra-must-not-import-domain',
    ]

    for (const pair of expectedPairs) {
      expect(depcruise).toContain(`name: '${pair}'`)
    }
  })

  test('two-layer config produces exactly one pair rule', () => {
    const config = {
      ...defaultConfig('/root'),
      architecture: {
        layers: [
          { name: 'cli', paths: ['src/cli/'], pure: false },
          { name: 'domain', paths: ['src/domain/'], pure: true },
        ],
        moduleRoots: [],
        entryPoints: ['index.ts'],
        maxFileLines: 400,
        maxFunctionLines: 50,
        maxFunctionLinesBaseline: {},
        ioExemptions: [],
        restrictedSyntax: [],
        ioMessage: 'Import {module} only from a declared I/O adapter; elsewhere, pass the value in as an argument.',
        impureImports: [],
      },
    }
    const plan = planGuards(config)
    const depcruise = plan.files.find((f) => f.path === 'anchoring.depcruise.cjs')?.body ?? ''

    expect(depcruise).toContain("name: 'layer-domain-must-not-import-cli'")
    expect(depcruise).not.toContain('layer-cli-must-not-import-domain')
  })

  test('pure layer produces restricted-imports/globals/properties block; no pure layer produces none', () => {
    const withPure = planGuards({
      ...defaultConfig('/root'),
      architecture: SAMPLE_ARCH,
    })
    const mjsWithPure = withPure.files.find((f) => f.path === 'anchoring.guards.mjs')?.body ?? ''
    expect(mjsWithPure).toContain('no-restricted-globals')
    expect(mjsWithPure).toContain('no-restricted-properties')
    expect(mjsWithPure).toContain('no-restricted-syntax')
    // `new Date()` is banned in the pure layer only; the import ban is wider than the pure
    // layer now and is asserted separately below.
    expect(mjsWithPure).toContain('NewExpression[callee.name="Date"]')
    expect(mjsWithPure).toContain('domain is the pure layer')

    const withoutPure = planGuards({
      ...defaultConfig('/root'),
      architecture: {
        ...SAMPLE_ARCH,
        layers: SAMPLE_ARCH.layers.map((l) => ({ ...l, pure: false })),
      },
    })
    const mjsWithoutPure = withoutPure.files.find((f) => f.path === 'anchoring.guards.mjs')?.body ?? ''
    expect(mjsWithoutPure).not.toContain('no-restricted-globals')
    expect(mjsWithoutPure).not.toContain('no-restricted-properties')
    expect(mjsWithoutPure).not.toContain('NewExpression[callee.name="Date"]')

    // The impure-import ban survives with no pure layer: it covers every governed file,
    // minus the declared adapters. Purity narrows *which* extra rules apply, not whether
    // the codebase is allowed to reach for node:fs at random.
    expect(mjsWithoutPure).toContain('no-restricted-imports')
  })

  test('moduleRoots produce one entry-only rule each and entryPoints appear in pattern', () => {
    const config = {
      ...defaultConfig('/root'),
      architecture: SAMPLE_ARCH,
    }
    const plan = planGuards(config)
    const depcruise = plan.files.find((f) => f.path === 'anchoring.depcruise.cjs')?.body ?? ''

    expect(depcruise).toContain("name: 'module-src-modules-entry-only'")
    expect(depcruise).toContain("name: 'module-packages-entry-only'")
    expect(depcruise).toContain('index\\.ts|index\\.tsx|index\\.js')
  })

  test('max-lines values come from config and max-lines-per-function is disabled for *.test.*', () => {
    const config = {
      ...defaultConfig('/root'),
      architecture: {
        ...SAMPLE_ARCH,
        maxFileLines: 250,
        maxFunctionLines: 35,
        maxFunctionLinesBaseline: {},
        ioExemptions: [],
        restrictedSyntax: [],
        ioMessage: 'Import {module} only from a declared I/O adapter; elsewhere, pass the value in as an argument.',
      },
    }
    const plan = planGuards(config)
    const guardsMjs = plan.files.find((f) => f.path === 'anchoring.guards.mjs')?.body ?? ''

    expect(guardsMjs).toContain('max: 250')
    expect(guardsMjs).toContain('max: 35')
    expect(guardsMjs).toContain("files: ['**/*.test.*', '**/*.spec.*']")
    expect(guardsMjs).toContain("'max-lines-per-function': 'off'")
  })

  test('generated .mjs is syntactically valid and default export is an array', async () => {
    const config = {
      ...defaultConfig('/root'),
      architecture: SAMPLE_ARCH,
    }
    const plan = planGuards(config)
    const mjsBody = plan.files.find((f) => f.path === 'anchoring.guards.mjs')?.body ?? ''

    const tempDir = makeTemp('kb-guards-eval-')
    const tempFile = join(tempDir, 'test-guards.mjs')
    writeFileSync(tempFile, mjsBody, 'utf8')

    try {
      const imported = await import(pathToFileURL(tempFile).href)
      expect(Array.isArray(imported.default)).toBe(true)
      expect(imported.default.length).toBeGreaterThanOrEqual(2)
    } finally {
      rmSync(tempDir, { recursive: true, force: true })
    }
  })
})

describe('checkGuards', () => {
  test('checkGuards returns ok when file exists and matches planned body', () => {
    const config = { ...defaultConfig('/root'), architecture: SAMPLE_ARCH }
    const plan = planGuards(config)
    const store = new Map<string, string>()
    for (const f of plan.files) {
      store.set(f.path, f.body)
    }

    const res = checkGuards(plan, (p) => store.get(p))
    expect(res.every((r) => r.state === 'ok')).toBe(true)
  })

  test('checkGuards returns missing when file does not exist', () => {
    const config = { ...defaultConfig('/root'), architecture: SAMPLE_ARCH }
    const plan = planGuards(config)
    const res = checkGuards(plan, () => undefined)
    expect(res.every((r) => r.state === 'missing')).toBe(true)
  })

  test('checkGuards returns stale when header hash differs', () => {
    const config = { ...defaultConfig('/root'), architecture: SAMPLE_ARCH }
    const plan = planGuards(config)
    const file = plan.files[0]
    expect(file).toBeDefined()
    if (!file) return

    const staleBody = file.body.replace(/\/\/ kb-guards-hash: [0-9a-f]+/, '// kb-guards-hash: 0000000000000000')
    const res = checkGuards(plan, (p) => (p === file.path ? staleBody : undefined))
    const checked = res.find((r) => r.path === file.path)
    expect(checked?.state).toBe('stale')
  })

  test('checkGuards returns hand-edited when hash matches but body differs', () => {
    const config = { ...defaultConfig('/root'), architecture: SAMPLE_ARCH }
    const plan = planGuards(config)
    const file = plan.files[0]
    expect(file).toBeDefined()
    if (!file) return

    const handEditedBody = `${file.body}\n// some manual comment`
    const res = checkGuards(plan, (p) => (p === file.path ? handEditedBody : undefined))
    const checked = res.find((r) => r.path === file.path)
    expect(checked?.state).toBe('hand-edited')
  })
})

describe('CLI kb guards', () => {
  function makeRepo(arch?: unknown, withPkgJson = true): string {
    const root = makeTemp('kb-guards-cli-')
    if (withPkgJson) {
      writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'test-pkg' }))
    }
    const configObj = arch ? { architecture: arch } : {}
    writeFileSync(join(root, 'anchoring.config.json'), JSON.stringify(configObj, null, 2))
    return root
  }

  test('missing architecture exits 1 and prints example', () => {
    const root = makeRepo(undefined)
    const out: string[] = []
    const err: string[] = []
    const code = run(['guards'], (t) => out.push(t), (t) => err.push(t), root)

    expect(code).toBe(1)
    expect(err.join('\n')).toContain('kb guards: no "architecture" block in anchoring.config.json — nothing to generate.')
    expect(err.join('\n')).toContain('Example "architecture" block to add to anchoring.config.json:')
  })

  test('missing package.json exits 1 and writes nothing', () => {
    const root = makeRepo(SAMPLE_ARCH, false)
    const out: string[] = []
    const err: string[] = []
    const code = run(['guards'], (t) => out.push(t), (t) => err.push(t), root)

    expect(code).toBe(1)
    expect(err.join('\n')).toContain('kb guards: generated checkers currently target TypeScript/JavaScript projects only.')
    expect(existsSync(join(root, 'anchoring.guards.mjs'))).toBe(false)
  })

  test('--dry-run writes nothing and prints full bodies', () => {
    const root = makeRepo(SAMPLE_ARCH)
    const out: string[] = []
    const err: string[] = []
    const code = run(['guards', '--dry-run'], (t) => out.push(t), (t) => err.push(t), root)

    expect(code).toBe(0)
    expect(existsSync(join(root, 'anchoring.guards.mjs'))).toBe(false)
    expect(existsSync(join(root, 'anchoring.depcruise.cjs'))).toBe(false)
    expect(out.join('\n')).toContain('--- anchoring.depcruise.cjs ---')
    expect(out.join('\n')).toContain('--- anchoring.guards.mjs ---')
  })

  test('no flags writes both files and prints compose instructions', () => {
    const root = makeRepo(SAMPLE_ARCH)
    const out: string[] = []
    const err: string[] = []
    const code = run(['guards'], (t) => out.push(t), (t) => err.push(t), root)

    expect(code).toBe(0)
    expect(existsSync(join(root, 'anchoring.guards.mjs'))).toBe(true)
    expect(existsSync(join(root, 'anchoring.depcruise.cjs'))).toBe(true)
    expect(out.join('\n')).toContain('kb guards: wrote anchoring.depcruise.cjs')
    expect(out.join('\n')).toContain('kb guards: wrote anchoring.guards.mjs')
    expect(out.join('\n')).toContain('Add these two lines to compose the guards with your own config:')
  })

  test('--check exits 0 when both files are ok', () => {
    const root = makeRepo(SAMPLE_ARCH)
    run(['guards'], () => {}, () => {}, root)

    const out: string[] = []
    const err: string[] = []
    const code = run(['guards', '--check'], (t) => out.push(t), (t) => err.push(t), root)

    expect(code).toBe(0)
    expect(out.join('\n')).toContain('anchoring.depcruise.cjs: ok')
    expect(out.join('\n')).toContain('anchoring.guards.mjs: ok')
  })

  test('--check exits 1 on stale and hand-edited', () => {
    const root = makeRepo(SAMPLE_ARCH)
    run(['guards'], () => {}, () => {}, root)

    // Hand-edit one file
    const mjsPath = join(root, 'anchoring.guards.mjs')
    const originalMjs = existsSync(mjsPath)
    expect(originalMjs).toBe(true)
    writeFileSync(mjsPath, '// some edit\n' + writeFileSync) // broken content

    const out: string[] = []
    const code = run(['guards', '--check'], (t) => out.push(t), () => {}, root)
    expect(code).toBe(1)
  })
})
