/**
 * Generated architecture checkers.
 *
 * Generates configuration fragments for ESLint flat config (anchoring.guards.mjs)
 * and dependency-cruiser (anchoring.depcruise.cjs) derived directly from the
 * architecture block in anchoring.config.json.
 *
 * Pure module: no filesystem, no crypto, no clock, no process.
 */

import type { AnchoringConfig, Architecture } from './config.js'
import { fnv1a } from './fnv.js'

export interface GeneratedFile {
  readonly path: string        // repo-relative
  readonly body: string
}

export interface GuardsPlan {
  readonly files: readonly GeneratedFile[]
  readonly notes: readonly string[]
}

export type GuardFileState = 'ok' | 'missing' | 'stale' | 'hand-edited'

export interface GuardCheckResult {
  readonly path: string
  readonly state: GuardFileState
}

function canonicalJson(val: unknown): string {
  if (val === null || typeof val !== 'object') {
    return JSON.stringify(val)
  }
  if (Array.isArray(val)) {
    return `[${val.map(canonicalJson).join(',')}]`
  }
  const obj = val as Record<string, unknown>
  const sortedKeys = Object.keys(obj).sort()
  const entries = sortedKeys
    .filter((k) => obj[k] !== undefined)
    .map((k) => `${JSON.stringify(k)}:${canonicalJson(obj[k])}`)
  return `{${entries.join(',')}}`
}

export function guardsHash(architecture: Architecture): string {
  return fnv1a(canonicalJson(architecture))
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * A directory constrains a prefix; a file must match exactly.
 *
 * Without the `$`, the layer path `src/verify.ts` would also claim `src/verify.ts.bak` and
 * any future `src/verify.tsx` - a checker quietly governing files nobody assigned to it.
 */
function pathToPattern(p: string): string {
  return p.endsWith('/') ? escapeRegex(p) : `${escapeRegex(p)}$`
}

function pathsToPattern(paths: readonly string[]): string {
  if (paths.length === 0) return ''
  const escaped = paths.map(pathToPattern)
  return escaped.length === 1 ? `^${escaped[0]}` : `^(${escaped.join('|')})`
}

function generateHeader(hash: string): string {
  return [
    '// GENERATED BY `kb guards` — DO NOT EDIT.',
    '// Source of truth: anchoring.config.json → architecture',
    `// kb-guards-hash: ${hash}`,
    '// Regenerate with: npx kb guards',
    '',
  ].join('\n')
}

function generateDepcruise(arch: Architecture, hash: string): string {
  const header = generateHeader(hash)
  const rules: string[] = []

  // 1. no-circular (always emitted)
  rules.push(`    {
      name: 'no-circular',
      severity: 'error',
      comment: 'Circular dependencies break architectural hierarchy and prevent isolated testing.',
      from: {},
      to: {
        circular: true,
      },
    }`)

  // 2. layer-<lower>-must-not-import-<higher>
  const layers = arch.layers
  for (let i = 0; i < layers.length; i++) {
    const higher = layers[i]
    if (!higher) continue
    for (let j = i + 1; j < layers.length; j++) {
      const lower = layers[j]
      if (!lower) continue
      const ruleName = `layer-${lower.name}-must-not-import-${higher.name}`
      const comment = `${lower.name} layer sits below ${higher.name} in the architecture: importing upward is forbidden.`
      const fromPattern = pathsToPattern(lower.paths)
      const toPattern = pathsToPattern(higher.paths)

      rules.push(`    {
      name: '${ruleName}',
      severity: 'error',
      comment: '${comment}',
      from: {
        path: '${fromPattern}',
      },
      to: {
        path: '${toPattern}',
      },
    }`)
    }
  }

  // 3. module-<root>-entry-only
  const entryPattern = arch.entryPoints.map(escapeRegex).join('|')
  for (const root of arch.moduleRoots) {
    const rootName = root.replace(/\/+$/, '').replace(/[^a-zA-Z0-9-]/g, '-')
    const escapedRoot = escapeRegex(root)
    rules.push(`    {
      name: 'module-${rootName}-entry-only',
      severity: 'error',
      comment: 'Cross-module imports must go through the module\\'s entry point.',
      from: {
        pathNot: '^${escapedRoot}$1/.+',
      },
      to: {
        path: '^${escapedRoot}([^/]+)/.+',
        pathNot: '^${escapedRoot}[^/]+/(${entryPattern})$',
      },
    }`)
  }

  const emptyComment =
    layers.length === 0 && arch.moduleRoots.length === 0
      ? '// No layers or moduleRoots configured yet in anchoring.config.json.\n'
      : ''

  const body = `${header}${emptyComment}module.exports = {
  forbidden: [
${rules.join(',\n')}
  ],
}
`
  return body
}

function globForPath(p: string): string {
  return p.endsWith('/') ? `${p}**/*` : p
}

/**
 * One `max-lines-per-function` override per file that is over the limit today, set to that
 * file's longest function *now* - the ratchet.
 *
 * A new file meets `maxFunctionLines` immediately; an exempt file can never get worse; and
 * the debt is a list somebody can watch shrink. Sorted by path so the emitted file stays
 * byte-stable.
 *
 * What stops this becoming a permanent amnesty is a test, not this comment: every entry is
 * pinned to the exact current worst, so it cannot be raised to wave a regression through,
 * and it cannot be left behind once the function is finally split.
 */
/**
 * The two size ceilings: source files, then test files.
 *
 * Test files need their own block because `layers[].paths` name source files, so without it
 * `max-lines` never sees a test at all. The two ceilings differ on purpose: a 900-line test
 * file is a real problem and keeps the file limit, while a 200-line `describe` body is not,
 * so the per-function limit stays off there.
 */
function generateSizeBlocks(arch: Architecture, targetFiles: string): readonly string[] {
  const ceilings = (functionRule: string): string => `  {
    files: [
${targetFiles}
    ],
    rules: {
      'max-lines': [
        'error',
        {
          max: ${arch.maxFileLines},
          skipBlankLines: true,
          skipComments: true,
        },
      ],
      ${functionRule},
    },
  }`

  return [
    ceilings(`'max-lines-per-function': [
        'error',
        {
          max: ${arch.maxFunctionLines},
          skipBlankLines: true,
          skipComments: true,
        },
      ]`),
    ceilings("'max-lines-per-function': 'off'").replace(
      `files: [
${targetFiles}
    ]`,
      "files: ['**/*.test.*', '**/*.spec.*']",
    ),
  ]
}

function generateBaselineBlocks(arch: Architecture): readonly string[] {
  return Object.entries(arch.maxFunctionLinesBaseline)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(
      ([file, max]) => `  {
    files: ['${file}'],
    rules: {
      'max-lines-per-function': [
        'error',
        {
          max: ${max},
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  }`,
    )
}

/** The impure-import ban, over every governed file except the declared I/O adapters. */
function generateImportBlock(arch: Architecture, targetFiles: string): readonly string[] {
  // Wider than the pure layer on purpose. `node:fs` in an app-layer module is just as much
  // a boundary violation as in the domain, and the exemption list names the adapters that
  // exist to do exactly that.
  const exemptions = [...arch.ioExemptions, '**/*.test.*', '**/*.spec.*']
  const importPatterns = arch.impureImports
    .map(
      (mod) =>
        `          {
            group: ['${mod}', '${mod}/*'],
            message: '${arch.ioMessage.replace(/{module}/g, mod).replace(/'/g, "\\'")}',
          },`,
    )
    .join('\n')

  return [
    `  {
    files: [
${targetFiles}
    ],
    ignores: [
${exemptions.map((e) => `      '${e}',`).join('\n')}
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
${importPatterns}
          ],
        },
      ],
    },
  }`,
  ]
}

/**
 * Project-declared syntax bans, then the pure layer's.
 *
 * The pure block repeats the project selectors. It has to: two config objects declaring one
 * rule do not merge - the later replaces the earlier - and this block is later. Omitting
 * them would silently switch them off for exactly the layer that needs them most, which is
 * the defect this file was rewritten to fix. See .anchor/incident/INC-0004.md.
 */
function generateSyntaxBlocks(arch: Architecture, targetFiles: string): readonly string[] {
  const quote = (text: string): string => text.replace(/'/g, "\\'")
  const projectSyntax = arch.restrictedSyntax.map(
    (r) =>
      `        {
          selector: '${quote(r.selector)}',
          message: '${quote(r.message)}',
        },`,
  )

  const out: string[] = []
  if (projectSyntax.length > 0) {
    out.push(`  {
    files: [
${targetFiles}
    ],
    rules: {
      'no-restricted-syntax': [
        'error',
${projectSyntax.join('\n')}
      ],
    },
  }`)
  }

  const pureLayer = arch.layers.find((l) => l.pure)
  if (!pureLayer) return out

  const purePaths = pureLayer.paths.map((p) => `      '${globForPath(p)}',`).join('\n')
  const pureSyntax = [
    ...projectSyntax,
    `        {
          selector: 'NewExpression[callee.name="Date"]',
          message: '${pureLayer.name} is the pure layer: pass the value in as an argument instead of constructing a Date.',
        },`,
  ]

  out.push(`  {
    files: [
${purePaths}
    ],
    ignores: ['**/*.test.*', '**/*.spec.*'],
    rules: {
      'no-restricted-syntax': [
        'error',
${pureSyntax.join('\n')}
      ],
      'no-restricted-globals': [
        'error',
        {
          name: 'fetch',
          message: '${pureLayer.name} is the pure layer: pass the value in as an argument instead of using global fetch.',
        },
        {
          name: 'crypto',
          message: '${pureLayer.name} is the pure layer: pass the value in as an argument instead of using global crypto.',
        },
      ],
      'no-restricted-properties': [
        'error',
        {
          object: 'Math',
          property: 'random',
          message: '${pureLayer.name} is the pure layer: pass the value in as an argument instead of calling Math.random.',
        },
        {
          object: 'Date',
          property: 'now',
          message: '${pureLayer.name} is the pure layer: pass the value in as an argument instead of calling Date.now.',
        },
      ],
    },
  }`)

  return out
}

/**
 * Which files the project-wide rules cover.
 *
 * `governedPaths` first, as a directory glob, with the enumerated layer paths only as a
 * fallback. Enumerating files alone leaves a hole exactly where it hurts: a module somebody
 * adds before registering it in the matrix would match no block at all, so it would carry
 * no size ceiling and no import ban - unguarded precisely while it is newest and least
 * reviewed. A directory glob has no such gap.
 */
function governedGlobs(config: AnchoringConfig, arch: Architecture): readonly string[] {
  const governed = config.governedPaths.map(globForPath)
  const roots = arch.moduleRoots.map(globForPath)
  if (governed.length > 0) return [...governed, ...roots]
  return [...arch.layers.flatMap((layer) => layer.paths.map(globForPath)), ...roots]
}

function generateGuardsMjs(config: AnchoringConfig, arch: Architecture, hash: string): string {
  const header = generateHeader(hash)
  const allTargetPaths = governedGlobs(config, arch)

  const targetFiles =
    allTargetPaths.length > 0
      ? allTargetPaths.map((p) => `      '${p}',`).join('\n')
      : "      '**/*',"

  const blocks: string[] = []

  blocks.push(...generateSizeBlocks(arch, targetFiles))
  blocks.push(...generateBaselineBlocks(arch))

  blocks.push(...generateImportBlock(arch, targetFiles))
  blocks.push(...generateSyntaxBlocks(arch, targetFiles))

  const body = `${header}export default [
${blocks.join(',\n')}
]
`
  return body
}

export const COMPOSE_INSTRUCTIONS = `Add these two lines to compose the guards with your own config:

  eslint.config.js         import anchoringGuards from './anchoring.guards.mjs'
                           export default [ ...anchoringGuards, /* your config */ ]

  .dependency-cruiser.cjs  const anchoring = require('./anchoring.depcruise.cjs')
                           forbidden: [ ...anchoring.forbidden, /* your rules */ ]

  CI                       npx kb guards --check && npx eslint . && npx depcruise src`

export function planGuards(config: AnchoringConfig): GuardsPlan {
  if (!config.architecture) {
    return { files: [], notes: [] }
  }

  const hash = guardsHash(config.architecture)
  const depcruise = generateDepcruise(config.architecture, hash)
  const guardsMjs = generateGuardsMjs(config, config.architecture, hash)

  return {
    files: [
      { path: 'anchoring.depcruise.cjs', body: depcruise },
      { path: 'anchoring.guards.mjs', body: guardsMjs },
    ],
    notes: [COMPOSE_INSTRUCTIONS],
  }
}

/**
 * Content equality that ignores the line ending, because git decides that, not the author.
 *
 * On Windows with `core.autocrlf=true` a fresh clone writes CRLF while this generator writes
 * LF, so a byte comparison reported `hand-edited` on a file nobody had touched - a drift
 * detector raising a false alarm on the very first checkout, which is a detector people
 * learn to ignore. `.gitattributes` pins the checked-out form; this makes the check correct
 * even where it is not.
 */
function sameContent(a: string, b: string): boolean {
  const lf = (text: string): string => text.replace(/\r\n?/g, '\n')
  return lf(a) === lf(b)
}

export function checkGuards(
  plan: GuardsPlan,
  read: (path: string) => string | undefined,
): readonly GuardCheckResult[] {
  const results: GuardCheckResult[] = []

  for (const file of plan.files) {
    const actual = read(file.path)
    if (actual === undefined) {
      results.push({ path: file.path, state: 'missing' })
      continue
    }

    if (sameContent(actual, file.body)) {
      results.push({ path: file.path, state: 'ok' })
      continue
    }

    const actualHashMatch = actual.match(/\/\/ kb-guards-hash: ([0-9a-fA-F]+)/)
    const plannedHashMatch = file.body.match(/\/\/ kb-guards-hash: ([0-9a-fA-F]+)/)

    if (
      !actualHashMatch ||
      !plannedHashMatch ||
      actualHashMatch[1] !== plannedHashMatch[1]
    ) {
      results.push({ path: file.path, state: 'stale' })
    } else {
      results.push({ path: file.path, state: 'hand-edited' })
    }
  }

  return results
}
