/**
 * Generated architecture checkers.
 *
 * Generates configuration fragments for ESLint flat config (anchoring.guards.mjs)
 * and dependency-cruiser (anchoring.depcruise.cjs) derived directly from the
 * architecture block in anchoring.config.json.
 *
 * Pure module: no filesystem, no crypto, no clock, no process.
 */

import type { AnchoringConfig, Architecture } from './config.js'

export interface GeneratedFile {
  readonly path: string        // repo-relative
  readonly body: string
}

export interface GuardsPlan {
  readonly files: readonly GeneratedFile[]
  readonly notes: readonly string[]
}

export type GuardFileState = 'ok' | 'missing' | 'stale' | 'hand-edited'

export interface GuardCheckResult {
  readonly path: string
  readonly state: GuardFileState
}

function canonicalJson(val: unknown): string {
  if (val === null || typeof val !== 'object') {
    return JSON.stringify(val)
  }
  if (Array.isArray(val)) {
    return `[${val.map(canonicalJson).join(',')}]`
  }
  const obj = val as Record<string, unknown>
  const sortedKeys = Object.keys(obj).sort()
  const entries = sortedKeys
    .filter((k) => obj[k] !== undefined)
    .map((k) => `${JSON.stringify(k)}:${canonicalJson(obj[k])}`)
  return `{${entries.join(',')}}`
}

export function guardsHash(architecture: Architecture): string {
  const str = canonicalJson(architecture)
  let hash = 0xcbf29ce484222325n
  const prime = 0x100000001b3n
  for (let i = 0; i < str.length; i++) {
    hash ^= BigInt(str.charCodeAt(i))
    hash = (hash * prime) & 0xffffffffffffffffn
  }
  return hash.toString(16).padStart(16, '0')
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function pathsToPattern(paths: readonly string[]): string {
  if (paths.length === 0) return ''
  const escaped = paths.map(escapeRegex)
  return escaped.length === 1 ? `^${escaped[0]}` : `^(${escaped.join('|')})`
}

function generateHeader(hash: string): string {
  return [
    '// GENERATED BY `kb guards` — DO NOT EDIT.',
    '// Source of truth: anchoring.config.json → architecture',
    `// kb-guards-hash: ${hash}`,
    '// Regenerate with: npx kb guards',
    '',
  ].join('\n')
}

function generateDepcruise(arch: Architecture, hash: string): string {
  const header = generateHeader(hash)
  const rules: string[] = []

  // 1. no-circular (always emitted)
  rules.push(`    {
      name: 'no-circular',
      severity: 'error',
      comment: 'Circular dependencies break architectural hierarchy and prevent isolated testing.',
      from: {},
      to: {
        circular: true,
      },
    }`)

  // 2. layer-<lower>-must-not-import-<higher>
  const layers = arch.layers
  for (let i = 0; i < layers.length; i++) {
    const higher = layers[i]
    if (!higher) continue
    for (let j = i + 1; j < layers.length; j++) {
      const lower = layers[j]
      if (!lower) continue
      const ruleName = `layer-${lower.name}-must-not-import-${higher.name}`
      const comment = `${lower.name} layer sits below ${higher.name} in the architecture: importing upward is forbidden.`
      const fromPattern = pathsToPattern(lower.paths)
      const toPattern = pathsToPattern(higher.paths)

      rules.push(`    {
      name: '${ruleName}',
      severity: 'error',
      comment: '${comment}',
      from: {
        path: '${fromPattern}',
      },
      to: {
        path: '${toPattern}',
      },
    }`)
    }
  }

  // 3. module-<root>-entry-only
  const entryPattern = arch.entryPoints.map(escapeRegex).join('|')
  for (const root of arch.moduleRoots) {
    const rootName = root.replace(/\/+$/, '').replace(/[^a-zA-Z0-9-]/g, '-')
    const escapedRoot = escapeRegex(root)
    rules.push(`    {
      name: 'module-${rootName}-entry-only',
      severity: 'error',
      comment: 'Cross-module imports must go through the module\\'s entry point.',
      from: {
        pathNot: '^${escapedRoot}$1/.+',
      },
      to: {
        path: '^${escapedRoot}([^/]+)/.+',
        pathNot: '^${escapedRoot}[^/]+/(${entryPattern})$',
      },
    }`)
  }

  const emptyComment =
    layers.length === 0 && arch.moduleRoots.length === 0
      ? '// No layers or moduleRoots configured yet in anchoring.config.json.\n'
      : ''

  const body = `${header}${emptyComment}module.exports = {
  forbidden: [
${rules.join(',\n')}
  ],
}
`
  return body
}

function globForPath(p: string): string {
  return p.endsWith('/') ? `${p}**/*` : p
}

function generateGuardsMjs(arch: Architecture, hash: string): string {
  const header = generateHeader(hash)
  const allTargetPaths: string[] = []

  for (const layer of arch.layers) {
    for (const p of layer.paths) {
      allTargetPaths.push(globForPath(p))
    }
  }
  for (const root of arch.moduleRoots) {
    allTargetPaths.push(globForPath(root))
  }

  const targetFiles =
    allTargetPaths.length > 0
      ? allTargetPaths.map((p) => `      '${p}',`).join('\n')
      : "      '**/*',"

  const blocks: string[] = []

  // Block 1: size ceilings
  blocks.push(`  {
    files: [
${targetFiles}
    ],
    rules: {
      'max-lines': [
        'error',
        {
          max: ${arch.maxFileLines},
          skipBlankLines: true,
          skipComments: true,
        },
      ],
      'max-lines-per-function': [
        'error',
        {
          max: ${arch.maxFunctionLines},
          skipBlankLines: true,
          skipComments: true,
        },
      ],
    },
  }`)

  // Block 2: test files.
  //
  // `layers[].paths` name source files, so without this block `max-lines` never sees a
  // test file at all. The two ceilings are treated differently on purpose: a 900-line
  // test file is a real problem and keeps the file limit, while a 200-line `describe`
  // body is not, so the function limit stays off.
  blocks.push(`  {
    files: ['**/*.test.*', '**/*.spec.*'],
    rules: {
      'max-lines': [
        'error',
        {
          max: ${arch.maxFileLines},
          skipBlankLines: true,
          skipComments: true,
        },
      ],
      'max-lines-per-function': 'off',
    },
  }`)

  // Block 3: pure layer
  const pureLayer = arch.layers.find((l) => l.pure)
  if (pureLayer) {
    const purePaths = pureLayer.paths.map((p) => `      '${globForPath(p)}',`).join('\n')
    // `patterns` only, never `paths`. The group ['node:fs', 'node:fs/*'] already matches
    // the bare specifier, so emitting both made a single violation report twice:
    //   'node:fs' import is restricted from being used.
    //   'node:fs' import is restricted from being used by a pattern.
    const importPatterns = arch.impureImports
      .map(
        (mod) =>
          `          {\n            group: ['${mod}', '${mod}/*'],\n            message: '${pureLayer.name} is the pure layer: pass the value in as an argument instead of importing ${mod}.',\n          },`,
      )
      .join('\n')

    blocks.push(`  {
    files: [
${purePaths}
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
${importPatterns}
          ],
        },
      ],
      'no-restricted-globals': [
        'error',
        {
          name: 'Date',
          message: '${pureLayer.name} is the pure layer: pass the value in as an argument instead of using global Date.',
        },
        {
          name: 'fetch',
          message: '${pureLayer.name} is the pure layer: pass the value in as an argument instead of using global fetch.',
        },
        {
          name: 'crypto',
          message: '${pureLayer.name} is the pure layer: pass the value in as an argument instead of using global crypto.',
        },
      ],
      'no-restricted-properties': [
        'error',
        {
          object: 'Math',
          property: 'random',
          message: '${pureLayer.name} is the pure layer: pass the value in as an argument instead of calling Math.random.',
        },
        {
          object: 'Date',
          property: 'now',
          message: '${pureLayer.name} is the pure layer: pass the value in as an argument instead of calling Date.now.',
        },
      ],
    },
  }`)
  }

  const body = `${header}export default [
${blocks.join(',\n')}
]
`
  return body
}

export const COMPOSE_INSTRUCTIONS = `Add these two lines to compose the guards with your own config:

  eslint.config.js         import anchoringGuards from './anchoring.guards.mjs'
                           export default [ ...anchoringGuards, /* your config */ ]

  .dependency-cruiser.cjs  const anchoring = require('./anchoring.depcruise.cjs')
                           forbidden: [ ...anchoring.forbidden, /* your rules */ ]

  CI                       npx kb guards --check && npx eslint . && npx depcruise src`

export function planGuards(config: AnchoringConfig): GuardsPlan {
  if (!config.architecture) {
    return { files: [], notes: [] }
  }

  const hash = guardsHash(config.architecture)
  const depcruise = generateDepcruise(config.architecture, hash)
  const guardsMjs = generateGuardsMjs(config.architecture, hash)

  return {
    files: [
      { path: 'anchoring.depcruise.cjs', body: depcruise },
      { path: 'anchoring.guards.mjs', body: guardsMjs },
    ],
    notes: [COMPOSE_INSTRUCTIONS],
  }
}

export function checkGuards(
  plan: GuardsPlan,
  read: (path: string) => string | undefined,
): readonly GuardCheckResult[] {
  const results: GuardCheckResult[] = []

  for (const file of plan.files) {
    const actual = read(file.path)
    if (actual === undefined) {
      results.push({ path: file.path, state: 'missing' })
      continue
    }

    if (actual === file.body) {
      results.push({ path: file.path, state: 'ok' })
      continue
    }

    const actualHashMatch = actual.match(/\/\/ kb-guards-hash: ([0-9a-fA-F]+)/)
    const plannedHashMatch = file.body.match(/\/\/ kb-guards-hash: ([0-9a-fA-F]+)/)

    if (
      !actualHashMatch ||
      !plannedHashMatch ||
      actualHashMatch[1] !== plannedHashMatch[1]
    ) {
      results.push({ path: file.path, state: 'stale' })
    } else {
      results.push({ path: file.path, state: 'hand-edited' })
    }
  }

  return results
}
